apiVersion: v1
kind: ServiceAccount
metadata:
  name: virtual-kubelet
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtual-kubelet
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - delete
      - get
      - list
      - watch
      - patch
      - create
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - create
      - get
      - patch
  - apiGroups:
      - ""
    resources:
      - nodes/status
    verbs:
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - pods/status
    verbs:
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
      - slurm.sylabs.io
    resources:
      - slurmjobs
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: virtual-kubelet
subjects:
  - kind: ServiceAccount
    name: virtual-kubelet
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: virtual-kubelet
---
apiVersion: v1
kind: Pod
metadata:
  name: configurator
spec:
  serviceAccountName: virtual-kubelet
  containers:
    - name: configurator
      image: cali4888/cfg:0.0.1
      imagePullPolicy: Always
      args:
        - --sock
        - "/syslurm/red-box.sock"
      volumeMounts:
        - name: syslurm-mount
          mountPath: /syslurm
      env:
        - name: HOST_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: KUBELET_IMAGE
          value: "cali4888/vk:0.0.1"
  volumes:
    - name: syslurm-mount
      hostPath:
        path: /var/run/syslurm
        type: Directory
