apiVersion: v1
kind: ServiceAccount
metadata:
  name: slurm-rd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: slurm-rd
rules:
  - apiGroups: [""]
    resources: ["nodes", "nodes/status"]
    verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: slurm-rd
subjects:
  - kind: ServiceAccount
    name: slurm-rd
    namespace: default
roleRef:
  kind: ClusterRole
  name: slurm-rd
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: slurm-rd
spec:
  selector:
    matchLabels:
      name: slurm-rd
  template:
    metadata:
      labels:
        name: slurm-rd
    spec:
      serviceAccountName: slurm-rd
      containers:
      - name: slurm-rd
        image: cloud.sylabs.io/library/slurm/resource-daemon:staging
        imagePullPolicy: Always
        args: ["-slurm-config", "/etc/config/slurm"]
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: SLURM_CLUSTER_CONFIG
          valueFrom:
           configMapKeyRef:
             name: slurm-config
             key: config
        volumeMounts:
          - name: kubelet-dp
            mountPath: /var/lib/kubelet/device-plugins
          - name: slurm-cfg-map-vol
            mountPath: /etc/config
          - name: red-box-sock
            mountPath: /red-box.sock
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      volumes:
        - name: kubelet-dp
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: red-box-sock
          hostPath:
            path: /var/run/syslurm/red-box.sock
